# Generated by Django 3.2.9 on 2021-11-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='min_score',
            field=models.IntegerField(default=0, help_text='min score you need to pass the quiz.'),
        ),
    ]
